### ISSUE TITLE
作者很用心，顺便提个疑问？

### ISSUE THREAD

**Issue by linkaipeng** [tianzhijiexian/Android-Best-Practices#10]
平时用得比较多的那种判断` convertView` 是否为空再去决定`convertView`能否被复用。
它复用的原理是，同一种`viewType`的时候，只要`convertView`不为空，不管多少item都可以复用的。

但是你的这种方式，是否只是`item`自己复用自己的`view`呢？假如同种类型的`item`有100条，是不是创建100个view呢？因为看你的`TextItem`类里面貌似都是每次创建一个新的。

如理解错误，请指出。谢谢~

**Comment by tianzhijiexian** [comment]
很感谢你的支持，很希望能共同讨论。我的设计中，在converView不为空的时候才会去new出新的item。所以和之前的做法是完全一致的。假如同类型的item有100个，其实总共也就创建了一屏幕的item，不会出现重复创建的问题。这里你可以在mainActivity中打log看下~ 感谢你的评论

**Comment by zzz40500** [comment]
@linkaipeng  从代码中可以看出跟ViewHoder 数量一致

**Comment by lubeast** [comment]
@linkaipeng 并没有创建100个，其实是viewholder的同种类型但是不同表现形式On Oct 29, 2015, at 11:02 AM, linkaipeng <notifications@github.com> wrote:平时用得比较多的那种判断convertView 是否为空再去决定convertView能否被复用。
它复用的原理是，同一种viewType的时候，只要convertView不为空，不管多少item都可以复用的。但是你的这种方式，是否只是item自己复用自己的view呢？假如同种类型的item有100条，是不是创建100个view呢？因为看你的TextItem类里面貌似都是每次创建一个新的。如理解错误，请指出。谢谢~—Reply to this email directly or view it on GitHub.

**Comment by david-wei** [comment]
@lubeast 可以看一下CommonAdpater类的实现，它也是实现了重用机制的，并不会创建那么多项。这里的getItemView方法只会在没拿到缓存的view，新建的时候调用的。

**Comment by lubeast** [comment]
@david-wei 帅哥~你应该艾特linkaipeng....我是邮件回复的，并不是我的提问，可能看上去杂乱了一点。。哈哈

**Comment by tianzhijiexian** [comment]
你好，解决了么？如果已经解决，可以close掉的~
