### ISSUE TITLE
log那篇文章

### ISSUE THREAD

**Issue by ihrthk** [tianzhijiexian/Android-Best-Practices#13]
第一个问题：object,map,list,array。能不能和在一起，用一个方法
第二个问题：要支持文件写入，以便后续查找

**Comment by tianzhijiexian** [comment]
我觉得你说的很在理，第一个可能需要做一些处理，但没啥问题。第二个文件写入的话就需要把这个库的 定制性增强，我可能会着重增加第一个功能，第二个看后期的时间和安排。

**Comment by tianzhijiexian** [comment]
你不用close，等我完善了后，我会告诉你，那时候你再close吧。

**Comment by tianzhijiexian** [comment]
第一个问题，目前的类中其实这些东西都是一个方法，如果你下了之前的demo就会发现都是一个object方法进行输出的。第二个问题，我不建议log的工具类做保存文件的事情，你可以去截获系统的所有log，然后把他进行存储。这样一劳永逸，而且无入侵。原本的log库作者最近很忙，我自己fork了一个：https://github.com/tianzhijiexian/logger 增加了一些功能
