### ISSUE TITLE
lib编译的时候找不到logger file

### ISSUE THREAD

**Issue by androidShuang** [tianzhijiexian/Android-Best-Practices#15]
Failed to resolve: com.github.tianzhijiexian:logger:2e4dca7ea8
请问是什么原因啊？设置问题？

**Comment by tianzhijiexian** [comment]
compile 'com.github.tianzhijiexian:logger:1.1.4' 试试

**Comment by androidShuang** [comment]
Failed to resolve: com.github.tianzhijiexian:logger:1.1.4
依旧是这样，你没问题么？

**Comment by tianzhijiexian** [comment]
![image](https://cloud.githubusercontent.com/assets/9552155/12030075/b26b4dda-ae33-11e5-9468-d0d365ce3a54.png)
试试， 在最外层加上这个
