### ISSUE TITLE
Log最佳实践中获取类名的问题

### ISSUE THREAD

**Issue by cmicat** [tianzhijiexian/Android-Best-Practices#17]
为什么不使用以下方式定义LOG_TAG
`private static final String LOG_TAG = MainActivity.class.getSimpleName();`
这是google给的方法，看上去比getClassName()函数简洁很多
最后的结果：
对于`MainActivity`
`LOG_TAG = "MainActivity"`

**Comment by brucezz** [comment]
这样的话，要在每个类里都要写这行代码吧，虽然AS可以通过设置Class文件模板来实现自动完成这行代码。
在Log工具类里实现也比较cool～ :)
