### ISSUE TITLE
停止更新了吗？

### ISSUE THREAD

**Issue by DanteAndroid** [tianzhijiexian/Android-Best-Practices#19]
写的挺好的

**Comment by tianzhijiexian** [comment]
班神别急，这个不是停更了。而是目前的文章没有与时俱进，我会结合最新的技术进行修改和更新。后期准备发intent实践和第三方登录分享的实践。
现在文章发布后并不是就完事的，我还在不断的做修改。所以发的这几篇我都还在继续修改和补充。此外，因为发的文章中引入了我的库，我必须要保证我的库没问题，并且能经受住考验后才能更新文章。

**Comment by tianzhijiexian** [comment]
刚刚更新了一篇，比较短。但是我一直在用，很实用的说。

**Comment by DanteAndroid** [comment]
Thx
