### ISSUE TITLE
关于通知栏的一个问题

### ISSUE THREAD

**Issue by ChoicesWang** [tianzhijiexian/Android-Best-Practices#2]
在第一个方法中，StatusBarManager 的对象是从 mContext.getSystemService("statusbar") 获取的，然后利用反射调用了该对象的展开和关闭的方法。
但是在第二个JOOR，create了一个对象，然后调用了这个对象的相应方法。
在第二个方法中，创建的对象不是Context中的对象，所以我怀疑该方法不能起作用。我还没有写的代码验证，但是我感觉这是错的。
不知道我没有说清楚，如果我的理解有误，请指正。

**Comment by zzz40500** [comment]
是有效的,但是这里得到的是新的StatusBarManager 的实例,它有这样的构造函数.
源码 android.app.StatusBarManager  
76     StatusBarManager(Context context) {
77         mContext = context;
78     }
地址;http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/app/StatusBarManager.java?av=f
但是确实不应该产生新的对象.

**Comment by tianzhijiexian** [comment]
在写这里的时候是我的失误，我会去看看这点，然后改正。谢谢指出 @ChoicesWang

**Comment by tianzhijiexian** [comment]
Object service = mContext.getSystemService("statusbar");
Reflect.on(service).call(methodName); 

@ChoicesWang

**Comment by tianzhijiexian** [comment]
谢谢你的反馈，我马上就修改代码
