### ISSUE TITLE
我想加入

### ISSUE THREAD

**Issue by hanmichael** [tianzhijiexian/Android-Best-Practices#24]
您好， 我想加入， 谢谢您啦

**Comment by mjh0617** [comment]
没人阻止你




------------------ 原始邮件 ------------------
发件人: "hanmichael";<notifications@github.com>;
发送时间: 2016年5月18日(星期三) 中午12:06
收件人: "tianzhijiexian/Android-Best-Practices"<Android-Best-Practices@noreply.github.com>; 

主题: [tianzhijiexian/Android-Best-Practices] 我想加入 (#24)




您好， 我想加入， 谢谢您啦

**Comment by 121880399** [comment]
没人阻止你

**Comment by tianzhijiexian** [comment]
可以啊，可以说下你准备写哪方面的内容
