### ISSUE TITLE
关于守护进程拉起application初始化的问题

### ISSUE THREAD

**Issue by yuanjunli** [tianzhijiexian/Android-Best-Practices#26]
关于守护进程拉起application初始化的问题，测试结果如下：小米推送是在点击 推送通知后才会拉起，因为用户点击推送消息的时间点不一样，不存在问题；而个推是在守护进程唤醒后会走application。会存在你说的情况。

**Comment by tianzhijiexian** [comment]
感谢指出个推的案例，谢谢分享。

**Comment by tianzhijiexian** [comment]
小米这块如果是透传，并且app被杀死的时，点击后会启动application。如果是系统的通知，也是类似。但如果app已经启动，那么则不影响。我是这么理解的，您下下是否符合你的意思。

**Comment by yuanjunli** [comment]
对的。

**Comment by tianzhijiexian** [comment]
那我这里就先不去改文章内容了，因为原文中拉起application是一个注意点，所以应该没什么问题。

**Comment by yuanjunli** [comment]
原文说道：因为推送服务的复活会启动application，即唤醒应用。所以千万不要在application启动的时候进行网络请求的操作。因为一旦开始推送，大量用户的应用会被唤醒，然后再几分钟内会产生对于少数api的大量请求。 
     我的观点是在小米手机上，推送服务的服务并不会启动application。而是在用户点击推送的时候才会唤醒应用。因为用户点击通知的时机不一样，所以在我看来对后台压力不大。当然application应合适的继续网络请求这点是赞同的。
    恩，无须改文章内容，就是交流，没想到回复这么快。
