### ISSUE TITLE
关于Adapter的一点点意见和疑问

### ISSUE THREAD

**Issue by cctanfujun** [tianzhijiexian/Android-Best-Practices#27]
1. 关于AdapterItem接口的方法名字起的不是很好，bindview这个我觉得有歧义，因为recyclerview本身的adapter里面两个回调onCreateViewHolder和onBindViewholder,我们会在onCreateViewHolder做findById在onBindViewHolder做数据绑定。
2.关于局部刷新，文章中只是实现了刷新单条数据，而没有实现刷新单条数据里面的某个控件，对于RecyclerView可以使用三个参数的重载方法实现public void onBindViewHolder(VHholder, int position, List<Object> payloads) ，不然比如有加载图片的话可能会引起图片闪烁。
3.如果实践能够结合diffutil就更好

以上

**Comment by tianzhijiexian** [comment]
create vh和bind vh是对于vh来说的，它的含义在于建立vh和将vh绑定到recycleview上。但item中的bindviews是对item而言的，意义是给item绑定它自己的view视图。bind的参考butterknift，这个问题应该不大。

局部刷新的问题是仅仅刷新了一个item，但是对于item中的某个控件的内容没有做颗粒度更加详细的刷新，这个是承认的，这个也是之前没有更加细致的地方，我会去研究下您数说的api。

diffutil这个东西我其实一直想用，但是一直没找到合适的切合点。正如您所看到的，如果使用了observableArrayList，那么这个list在被操作的时候就会自动进行所需要的notify。如果用diffutil的话，就是要进行一次比较工作，然后再产生notify。

更多建议希望可以加 qq:460412008，我最近也在准备重写这篇文章，所以希望可以得到指导，谢谢~
