### ISSUE TITLE
获取类名可用  getClass().getCanonicalName

### ISSUE THREAD

**Issue by iptton** [tianzhijiexian/Android-Best-Practices#5]
不需要取 lastIndexOf(".")

**Comment by tianzhijiexian** [comment]
感谢提醒，但是我忘记了那里用到了 lastIndexOf(".")这个，可否指出。

**Comment by iptton** [comment]
https://github.com/tianzhijiexian/Android-Best-Practices/blob/master/2015.8/log/log.md 

/**
     * @return 当前的类名(simpleName)
     */
    private static String getClassName() {
        String result;
        StackTraceElement thisMethodStack = (new Exception()).getStackTrace()[2];
        result = thisMethodStack.getClassName();
        int lastIndex = result.lastIndexOf(".");
        result = result.substring(lastIndex + 1, result.length());
        return result;
    }

这里～

**Comment by tianzhijiexian** [comment]
其实这里还是有必要的，这个getClassName是StackTraceElement自身复写过的，和object中的方法不同。因此有特定的功能
