### ISSUE TITLE
L.object()方法不可用

### ISSUE THREAD

**Issue by lubeast** [tianzhijiexian/Android-Best-Practices#6]
在Logger中作者丢掉了这个方法，所以现在这么写是报错的。。

**Comment by tianzhijiexian** [comment]
那个作者就没有写这个方法，我是在它的基础上添加的。这个方法已经给他提交了pr，但是还没有merge。你直接下载我这个项目，就可以查看到这个方法的实现了。

**Comment by lubeast** [comment]
谢谢，我以为你直接拉的他的用的，已经解决。
