### ISSUE TITLE
使用那个您修改过的logger的时候 应该compile什么呢？

### ISSUE THREAD

**Issue by hunji66** [tianzhijiexian/Android-Best-Practices#7]
求指导。。

**Comment by tianzhijiexian** [comment]
你可以下载下这个项目，看里面是怎么做的。其实就是引入了原始的logger，然后在外面包了一个L类。如果你想要看完整的修改过后的logger，可以查看：https://github.com/tianzhijiexian/logger

**Comment by tianzhijiexian** [comment]
L的类在这里：https://github.com/tianzhijiexian/Android-Best-Practices/blob/master/lib/src/main/java/kale/debug/log/L.java ，在文章开头有说到，这里的所有例子都会提供下载的。项目里面都是有demo的。

**Comment by hunji66** [comment]
谢谢。。找的就是这个修改后的。。。

**Comment by tianzhijiexian** [comment]
以后发布的内容也都是提供demo预览的，如果是简单的项目，那么就会在这个项目中的demo中出现。如果是复杂的，我会另开一个项目。我真心感谢您愿意尝试我提供的思路和设计方案，很感谢您。

**Comment by hunji66** [comment]
嗯，谢谢啦。。

**Comment by tianzhijiexian** [comment]
很想了解到您在公司主要是负责什么的呢

**Comment by hunji66** [comment]
我刚刚毕业，目前正在找工作。

**Comment by SeanZom** [comment]
刚好需要这个，谢谢

**Comment by tianzhijiexian** [comment]
@hunji66  找工作不容易啊，祝顺利~

**Comment by hunji66** [comment]
已经找到了，谢谢。。
