### ISSUE TITLE
这是我写的AssemblyAdapter，我们可以互相交流一下

### ISSUE THREAD

**Issue by xiaopansky** [tianzhijiexian/Android-Best-Practices#8]
看了你前面提出的需求，发现我写的AssemblyAdapter https://github.com/xiaopansky/AssemblyAdapter 基本都满足，我们可以有进一步的交流

**Comment by tianzhijiexian** [comment]
已经看了您的项目，看到了他可以很灵活的进行配置。很希望进行进一步交流，可以通过邮件联系我。
