### ISSUE TITLE
关于AdapterItem的问题

### ISSUE THREAD

**Issue by david-wei** [tianzhijiexian/Android-Best-Practices#9]
今天刚看到了commonAdapter的实现，感觉非常不错。但是想到了一个如果AdapterItem中，有时候需要调用onActivityResult方法的回调，楼主有什么解决方案么？

**Comment by tianzhijiexian** [comment]
没什么好的解决方案，activity和简单类的交互一直是android中很麻烦的问题

**Comment by tianzhijiexian** [comment]
突然想到了让UIBlock实现adapterItem接口，这样就可以拿到回调。
